### ISSUE TITLE
APK for testing

### ISSUE THREAD

**Issue by hernic** [desyncr/freenet-mobile#1]
It should be nice to have a downloadable link for testing in the installation instructons (direct) link to assets.

A download button could be a solution.

**Comment by desyncr** [comment]
Will work on it. I can put a badge for direct APK download, thought I'd have to manually update it with each release :/

**Comment by desyncr** [comment]
Done, added a download button on the main README. Also available on the github page: https://desyncr.github.io/freenet-mobile/

Soon to be would be f-droid and play store badges.
